spring:
  application:
    name: gallery-service
server:
  port: 8300
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
image-service:
  ribbon:
    eureka:
      enabled: true
    serverListRefreshInterval: 15000